# Generated by Django 4.2.3 on 2023-07-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtd', models.PositiveIntegerField(choices=[(1, 'District 1'), (2, 'District 2')])),
                ('ideator_mobile', models.CharField(max_length=15)),
                ('ideator_gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('ideator_dob', models.DateField()),
                ('combinedInstitution', models.CharField(max_length=100)),
                ('ideator_cat', models.PositiveIntegerField(choices=[(4, 'Category 4'), (5, 'Category 5')])),
                ('ideator_year', models.PositiveIntegerField(choices=[(6, 'Year 6'), (7, 'Year 7')])),
                ('ideator_dep', models.CharField(max_length=100)),
                ('type_identity_no', models.CharField(max_length=100)),
                ('btnval', models.IntegerField()),
                ('Ideator_name', models.CharField(max_length=100, null=True)),
                ('cas_cat', models.CharField(max_length=50)),
                ('bank_acno', models.CharField(blank=True, max_length=100, null=True)),
                ('repeat_bank_acno', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
