# Generated by Django 4.2.3 on 2023-07-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_preregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='repeat_bank_acno',
        ),
    ]
