# Generated by Django 4.2.3 on 2023-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_data_repeat_bank_acno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='cas_cat',
        ),
        migrations.AlterField(
            model_name='data',
            name='districtd',
            field=models.PositiveIntegerField(choices=[(1, 'Thiruvananthapuram'), (2, 'Kollam'), (3, 'Pathanamthitta'), (4, 'Alappuzha'), (5, 'Kottayam'), (6, 'Idukki'), (7, 'Ernakulam'), (8, 'Thrissur'), (9, 'Palakkad'), (10, 'Malappuram'), (11, 'Kozhikode'), (12, 'Wayanad'), (13, 'Kannur'), (14, 'Kasaragod')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='ideator_dep',
            field=models.PositiveIntegerField(choices=[(1, 'Computer Science and Engineering'), (2, 'Electrical '), (3, 'Mechanical '), (4, 'Civil '), (5, 'Chemical '), (6, 'Biomedical ')]),
        ),
        migrations.AlterField(
            model_name='data',
            name='ideator_year',
            field=models.PositiveIntegerField(choices=[(1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')]),
        ),
    ]
